spring:
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080
#        username: actadmin
#        password: 123456
#        instance:
#          metadata:
#            user.name: snake
#            user.password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/stigeradmin?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
  cache:
    type: redis
    redis:
      time-to-live: 1m
  session:
    store-type: redis
server:
  port: 9999
  servlet:
    session:
      timeout: 30M
stiger:
  admin:
    web:
      security:
        remember-me-key: stiger-admin